{% set name = "optuna-dashboard" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optuna-dashboard-{{ version }}.tar.gz
  sha256: f4d59e159f0757c3a41cd1ff0c6d445ddbb3ca303bb72f29c2b35f856d445ccf

build:
  number: 0
  noarch: python
  entry_points:
    - optuna-dashboard = optuna_dashboard._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bottle
    - optuna >=2.7
    - packaging
    - python >=3.7
    - scikit-learn

test:
  imports:
    - optuna_dashboard
  commands:
    - pip check
    - optuna-dashboard --help
  requires:
    - pip

about:
  home: https://github.com/optuna/optuna-dashboard
  summary: Real-time dashboard for Optuna.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nabenabe0928
    - c-bata
    - g-votte
    - HideakiImamura
    - hvy
    - iwiwi
    - not522
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
